apiVersion: v1
kind: ConfigMap
metadata:
  name: mka-configmap
data:
  DB_NAME: udacity
  DB_USERNAME: admin
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: mka-secret
type: Opaque
data:
  password: UGFzc3cwcmQ=